/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.rutebanken.anshar.metrics.avro;

@org.apache.avro.specific.AvroGenerated
public interface Metrics {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Metrics\",\"namespace\":\"no.rutebanken.anshar.metrics.avro\",\"types\":[{\"type\":\"record\",\"name\":\"MetricRecord\",\"fields\":[{\"name\":\"recordedAtTime\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"hostname\",\"type\":\"string\"},{\"name\":\"labels\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"LabelRecord\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"string\"}]}},\"default\":[]},{\"name\":\"value\",\"type\":\"double\"}]}],\"messages\":{}}");

  @org.apache.avro.specific.AvroGenerated
  public interface Callback extends Metrics {
    public static final org.apache.avro.Protocol PROTOCOL = no.rutebanken.anshar.metrics.avro.Metrics.PROTOCOL;
  }
}