name: CI Build

on:
  push:
    branch:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONTAINER_REPO: ghcr.io/${{ github.repository_owner }}/anshar
      CONTAINER_REGISTRY_USER: ${{ github.repository_owner }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Run tests
        run: |
          # there is a test failure on CI, after that is resolved, this can be re-enabled
          # mvn --batch-mode test

      - name: Build container image with Jib, push to Github Container Repo
        run: |
          image_date=`date +%Y-%m-%dT%H-%M`
          mvn --batch-mode compile com.google.cloud.tools:jib-maven-plugin:build -Djib.to.tags=latest,$image_date
